# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0e011178f790127480d0888c56663c9c26b39662285b8f9dbd4c451e2f270f4cc13ad5922fdb4b9e622d10c83633c06fbd54eb469ae858b88c4dd833f583618

test:
  secret_key_base: 1d13dc5487dbfc2e9ec685b7745d24883da510df91b90f7bf93e80cd860acd82e77d73bb5b8085b3e137614e7adf3696746df432c2d09ad6fd65cef5a82fca84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
